import fs from "node:fs"
import path from "node:path"
import type { FinanceTransaction } from "@prisma/client"
import jsPDF from "jspdf"
import sharp from "sharp"

/** A4 in jsPDF default unit (pt) */
const A4_W = 595.28
const A4_H = 841.89

export async function tryLoadLetterheadPngDataUrl(): Promise<string | null> {
  const svgPath = path.join(process.cwd(), "public", "Joining Letter.svg")
  if (!fs.existsSync(svgPath)) return null
  try {
    const svgBuf = fs.readFileSync(svgPath)
    const pngBuf = await sharp(svgBuf)
      .resize({
        width: Math.round(A4_W * 2),
        height: Math.round(A4_H * 2),
        fit: "fill",
      })
      .png()
      .toBuffer()
    return `data:image/png;base64,${pngBuf.toString("base64")}`
  } catch {
    return null
  }
}

type SalaryTx = FinanceTransaction & {
  salaryEmployeeName?: string | null
  salaryBankAccount?: string | null
}

/** Fills first page with letterhead image + overlay text (call after tryLoadLetterheadPngDataUrl). */
export function drawSalarySlipOnPdf(
  doc: jsPDF,
  transaction: SalaryTx,
  letterheadDataUrl: string | null,
  generatedByName: string
) {
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()

  if (letterheadDataUrl) {
    try {
      doc.addImage(letterheadDataUrl, "PNG", 0, 0, pageW, pageH)
    } catch {
      /* fall through to text-only band */
    }
  }

  const employee =
    transaction.salaryEmployeeName?.trim() || transaction.title
  const account = transaction.salaryBankAccount?.trim()
  const amt = Number(transaction.amount)
  const txDate = new Date(transaction.date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  // Content card (matches web slip roughly — middle band)
  const padX = pageW * 0.08
  const padTop = pageH * 0.34
  const cardW = pageW - 2 * padX
  const cardH = Math.min(240, pageH * 0.32)

  doc.setFillColor(255, 255, 255)
  doc.setDrawColor(220, 220, 220)
  doc.roundedRect(padX, padTop, cardW, cardH, 6, 6, "FD")

  let y = padTop + 28
  doc.setTextColor(80, 80, 80)
  doc.setFontSize(9)
  doc.setFont("helvetica", "bold")
  doc.text("SALARY SLIP", pageW - padX, padTop + 18, { align: "right" })

  doc.setTextColor(30, 30, 30)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text(employee, padX + 14, y)
  y += 22

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(90, 90, 90)
  doc.text(`Payment date: ${txDate}`, padX + 14, y)
  y += 20

  doc.setTextColor(20, 20, 20)
  doc.setFontSize(11)
  doc.setFont("helvetica", "bold")
  doc.text("Amount (Rs)", padX + 14, y)
  doc.setFont("helvetica", "normal")
  doc.text(
    `Rs ${amt.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`,
    pageW - padX - 14,
    y,
    { align: "right" }
  )
  y += 22

  if (account) {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(10)
    doc.text("Account no.", padX + 14, y)
    y += 14
    doc.setFont("courier", "normal")
    doc.setFontSize(9)
    const acctLines = doc.splitTextToSize(account, cardW - 28)
    doc.text(acctLines, padX + 14, y)
    y += (Array.isArray(acctLines) ? acctLines.length : 1) * 12 + 6
  }

  if (transaction.description?.trim()) {
    y += 4
    doc.setFont("helvetica", "bold")
    doc.setFontSize(9)
    doc.setTextColor(90, 90, 90)
    doc.text("Notes", padX + 14, y)
    y += 12
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(40, 40, 40)
    const noteLines = doc.splitTextToSize(
      transaction.description.trim(),
      cardW - 28
    )
    doc.text(noteLines, padX + 14, y)
  }

  const footY = pageH - 36
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.setFont("helvetica", "normal")
  doc.text(`Generated by: ${generatedByName}`, padX, footY)
  doc.text(
    `Generated on: ${new Date().toLocaleString("en-US", {
      dateStyle: "long",
      timeStyle: "short",
    })}`,
    padX,
    footY + 12
  )
  doc.text(
    `Ledger ref: ${transaction.title}`,
    pageW - padX,
    footY,
    { align: "right" }
  )
}
